import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Branch Master",
  description: '"Generated by Torus',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex ">{children}</main>
      </body>
    </html>
  );
}
